name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel python3-dev build-essential libncurses-dev libreadline-dev libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libffi-dev libssl-dev libsndfile1 ffmpeg libgl1-mesa-dev

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Setup Android SDK
        run: |
          # Create Android SDK directory
          mkdir -p $HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
          
          # Download and extract command line tools
          cd $HOME
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          mv cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          
          # Accept licenses and install required packages
          echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"
          
          # Add to environment for next steps
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV

      - name: Initialize Buildozer
        run: |
          # Create buildozer.spec if it doesn't exist
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          
          # Update buildozer.spec with required settings
          sed -i 's/android.api = .*/android.api = 34/' buildozer.spec
          sed -i 's/android.minapi = .*/android.minapi = 21/' buildozer.spec
          sed -i 's/android.ndk = .*/android.ndk = 25b/' buildozer.spec
          sed -i 's/android.sdk = .*/android.sdk = 34/' buildozer.spec

      - name: Build the APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: change-bg-app
          path: bin/*.apk
